/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class Home extends javax.swing.JFrame {
public int ShowButtons = 0;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        NewBuyerButton.setVisible(false);
        UpdateBuyerButton.setVisible(false);
        BuyerDetailsButton.setVisible(false);
        DeleteBuyerButton.setVisible(false);
        NewProductButton.setVisible(false);
        UpdateProductButton.setVisible(false);
        ProductDetailsButton.setVisible(false);
        DeleteProductButton.setVisible(false);
        BillingButton.setVisible(false);
        LogoutButton.setVisible(false);
        
        NewBuyerLabel.setVisible(false);
        UpdateBuyerLabel.setVisible(false);
        BuyerDetailsLabel.setVisible(false);
        DeleteBuyerLabel.setVisible(false);
        NewProductLabel.setVisible(false);
        UpdateProductLabel.setVisible(false);
        ProductDetailsLabel.setVisible(false);
        DeleteProductLabel.setVisible(false);
        BillingLabel.setVisible(false);
        LogoutLabel.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewBuyerButton = new javax.swing.JButton();
        UpdateBuyerButton = new javax.swing.JButton();
        BuyerDetailsButton = new javax.swing.JButton();
        DeleteBuyerButton = new javax.swing.JButton();
        NewProductButton = new javax.swing.JButton();
        UpdateProductButton = new javax.swing.JButton();
        ProductDetailsButton = new javax.swing.JButton();
        DeleteProductButton = new javax.swing.JButton();
        BillingButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();
        NewBuyerLabel = new javax.swing.JLabel();
        UpdateBuyerLabel = new javax.swing.JLabel();
        DeleteBuyerLabel = new javax.swing.JLabel();
        BuyerDetailsLabel = new javax.swing.JLabel();
        NewProductLabel = new javax.swing.JLabel();
        UpdateProductLabel = new javax.swing.JLabel();
        ProductDetailsLabel = new javax.swing.JLabel();
        DeleteProductLabel = new javax.swing.JLabel();
        MenuButton = new javax.swing.JButton();
        BillingLabel = new javax.swing.JLabel();
        LogoutLabel = new javax.swing.JLabel();
        CloseLabel = new javax.swing.JLabel();
        HomeBackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(620, 320));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NewBuyerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeImages/new buyer.png"))); // NOI18N
        NewBuyerButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                NewBuyerButtonComponentShown(evt);
            }
        });
        NewBuyerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBuyerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NewBuyerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        UpdateBuyerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeImages/update buyer.png"))); // NOI18N
        UpdateBuyerButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                UpdateBuyerButtonComponentShown(evt);
            }
        });
        UpdateBuyerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBuyerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateBuyerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        BuyerDetailsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeImages/buyer details.png"))); // NOI18N
        BuyerDetailsButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BuyerDetailsButtonComponentShown(evt);
            }
        });
        getContentPane().add(BuyerDetailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        DeleteBuyerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeImages/delete buyer.png"))); // NOI18N
        DeleteBuyerButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DeleteBuyerButtonComponentShown(evt);
            }
        });
        getContentPane().add(DeleteBuyerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        NewProductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeImages/new product.png"))); // NOI18N
        NewProductButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                NewProductButtonComponentShown(evt);
            }
        });
        getContentPane().add(NewProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        UpdateProductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeImages/update product.png"))); // NOI18N
        UpdateProductButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                UpdateProductButtonComponentShown(evt);
            }
        });
        getContentPane().add(UpdateProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        ProductDetailsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeImages/product details.png"))); // NOI18N
        ProductDetailsButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ProductDetailsButtonComponentShown(evt);
            }
        });
        getContentPane().add(ProductDetailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, -1));

        DeleteProductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeImages/delete product.png"))); // NOI18N
        DeleteProductButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DeleteProductButtonComponentShown(evt);
            }
        });
        DeleteProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteProductButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        BillingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeImages/billing.png"))); // NOI18N
        BillingButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BillingButtonComponentShown(evt);
            }
        });
        getContentPane().add(BillingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, -1, -1));

        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeImages/Logout.png"))); // NOI18N
        LogoutButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                LogoutButtonComponentShown(evt);
            }
        });
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, -1, -1));

        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeImages/Close.png"))); // NOI18N
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, -1));

        NewBuyerLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NewBuyerLabel.setText("Adicionar");
        getContentPane().add(NewBuyerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        UpdateBuyerLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UpdateBuyerLabel.setText("Atualizar ");
        getContentPane().add(UpdateBuyerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        DeleteBuyerLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DeleteBuyerLabel.setText("Remover");
        getContentPane().add(DeleteBuyerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        BuyerDetailsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BuyerDetailsLabel.setText("Detalhes");
        getContentPane().add(BuyerDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        NewProductLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NewProductLabel.setText("Adicionar");
        getContentPane().add(NewProductLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        UpdateProductLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UpdateProductLabel.setText("Atualizar");
        getContentPane().add(UpdateProductLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, -1, -1));

        ProductDetailsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ProductDetailsLabel.setText("Detalhes");
        getContentPane().add(ProductDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, -1, -1));

        DeleteProductLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DeleteProductLabel.setText("Remover");
        getContentPane().add(DeleteProductLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, -1, -1));

        MenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeImages/menu.png"))); // NOI18N
        MenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuButtonMouseClicked(evt);
            }
        });
        getContentPane().add(MenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        BillingLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BillingLabel.setText("Conta");
        getContentPane().add(BillingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, -1, -1));

        LogoutLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LogoutLabel.setText("Logout");
        getContentPane().add(LogoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 80, -1, -1));

        CloseLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CloseLabel.setText("Fechar");
        getContentPane().add(CloseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 80, -1, -1));

        HomeBackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeImages/HomeBackground.png"))); // NOI18N
        getContentPane().add(HomeBackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteProductButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteProductButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Você tem certeza que deseja se desconectar?","Selecione:",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
         int a=JOptionPane.showConfirmDialog(null,"Tem certeza?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void MenuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuButtonMouseClicked
        if(ShowButtons==0){
            try{
                Thread.sleep(250);
                NewBuyerButton.setVisible(true);
                NewBuyerLabel.setVisible(true);
                
                ShowButtons=1;
            }
            catch(Exception e){
            }
        }else{
            NewBuyerButton.setVisible(false);
        UpdateBuyerButton.setVisible(false);
        BuyerDetailsButton.setVisible(false);
        DeleteBuyerButton.setVisible(false);
        NewProductButton.setVisible(false);
        UpdateProductButton.setVisible(false);
        ProductDetailsButton.setVisible(false);
        DeleteProductButton.setVisible(false);
        BillingButton.setVisible(false);
        LogoutButton.setVisible(false);
        
        NewBuyerLabel.setVisible(false);
        UpdateBuyerLabel.setVisible(false);
        BuyerDetailsLabel.setVisible(false);
        DeleteBuyerLabel.setVisible(false);
        NewProductLabel.setVisible(false);
        UpdateProductLabel.setVisible(false);
        ProductDetailsLabel.setVisible(false);
        DeleteProductLabel.setVisible(false);
        BillingLabel.setVisible(false);
        LogoutLabel.setVisible(false);
        ShowButtons=0;
        }
    }//GEN-LAST:event_MenuButtonMouseClicked

    private void NewBuyerButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_NewBuyerButtonComponentShown
        try{
                Thread.sleep(250);
                UpdateBuyerButton.setVisible(true);
                UpdateBuyerLabel.setVisible(true);
            }catch(Exception e){
            }
    }//GEN-LAST:event_NewBuyerButtonComponentShown

    private void UpdateBuyerButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_UpdateBuyerButtonComponentShown
        try{
                Thread.sleep(250);
                BuyerDetailsButton.setVisible(true);
                BuyerDetailsLabel.setVisible(true);
            }catch(Exception e){
            }
    }//GEN-LAST:event_UpdateBuyerButtonComponentShown

    private void BuyerDetailsButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BuyerDetailsButtonComponentShown
       try{
                Thread.sleep(250);
                DeleteBuyerButton.setVisible(true);
                DeleteBuyerLabel.setVisible(true);
            }catch(Exception e){
            }
    }//GEN-LAST:event_BuyerDetailsButtonComponentShown

    private void DeleteBuyerButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DeleteBuyerButtonComponentShown
        try{
                Thread.sleep(250);
                NewProductButton.setVisible(true);
                NewProductLabel.setVisible(true);
            }catch(Exception e){
            }
    }//GEN-LAST:event_DeleteBuyerButtonComponentShown

    private void NewProductButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_NewProductButtonComponentShown
        try{
                Thread.sleep(250);
                UpdateProductButton.setVisible(true);
                UpdateProductLabel.setVisible(true);
            }catch(Exception e){
            }
    }//GEN-LAST:event_NewProductButtonComponentShown

    private void UpdateProductButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_UpdateProductButtonComponentShown
        try{
                Thread.sleep(250);
                ProductDetailsButton.setVisible(true);
                ProductDetailsLabel.setVisible(true);
            }catch(Exception e){
            }
    }//GEN-LAST:event_UpdateProductButtonComponentShown

    private void ProductDetailsButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ProductDetailsButtonComponentShown
        try{
                Thread.sleep(250);
                DeleteProductButton.setVisible(true);
                DeleteProductLabel.setVisible(true);
            }catch(Exception e){
            }
    }//GEN-LAST:event_ProductDetailsButtonComponentShown

    private void DeleteProductButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DeleteProductButtonComponentShown
        try{
                Thread.sleep(250);
                BillingButton.setVisible(true);
                BillingLabel.setVisible(true);
            }catch(Exception e){
            }
    }//GEN-LAST:event_DeleteProductButtonComponentShown

    private void BillingButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BillingButtonComponentShown
        try{
                Thread.sleep(250);
                LogoutButton.setVisible(true);
                LogoutLabel.setVisible(true);
            }catch(Exception e){
            }
    }//GEN-LAST:event_BillingButtonComponentShown

    private void LogoutButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_LogoutButtonComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutButtonComponentShown

    private void NewBuyerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBuyerButtonActionPerformed
        new NewBuyer().setVisible(true);
    }//GEN-LAST:event_NewBuyerButtonActionPerformed

    private void UpdateBuyerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBuyerButtonActionPerformed
        new UpdateBuyer().setVisible(true);
    }//GEN-LAST:event_UpdateBuyerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BillingButton;
    private javax.swing.JLabel BillingLabel;
    private javax.swing.JButton BuyerDetailsButton;
    private javax.swing.JLabel BuyerDetailsLabel;
    private javax.swing.JButton CloseButton;
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JButton DeleteBuyerButton;
    private javax.swing.JLabel DeleteBuyerLabel;
    private javax.swing.JButton DeleteProductButton;
    private javax.swing.JLabel DeleteProductLabel;
    private javax.swing.JLabel HomeBackgroundLabel;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel LogoutLabel;
    private javax.swing.JButton MenuButton;
    private javax.swing.JButton NewBuyerButton;
    private javax.swing.JLabel NewBuyerLabel;
    private javax.swing.JButton NewProductButton;
    private javax.swing.JLabel NewProductLabel;
    private javax.swing.JButton ProductDetailsButton;
    private javax.swing.JLabel ProductDetailsLabel;
    private javax.swing.JButton UpdateBuyerButton;
    private javax.swing.JLabel UpdateBuyerLabel;
    private javax.swing.JButton UpdateProductButton;
    private javax.swing.JLabel UpdateProductLabel;
    // End of variables declaration//GEN-END:variables
}
