
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import javax.swing.JOptionPane;
import java.awt.Color;
import Dao.ConnectionProvider; 
import java.sql.*; 
import Bean.Buyer;


/**
 *
 * @author pedro
 */
public class NewBuyer extends javax.swing.JFrame {

    /**
     * Creates new form NewBuyer
     */
    public NewBuyer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewBuyerIcon = new javax.swing.JLabel();
        NewBuyerNameLabel = new javax.swing.JLabel();
        NewBuyerEmailLabel = new javax.swing.JLabel();
        NewBuyerCellphoneLabel = new javax.swing.JLabel();
        NewBuyerAddressLabel = new javax.swing.JLabel();
        NewBuyeGenderLabel = new javax.swing.JLabel();
        NewBuyerNameTextField = new javax.swing.JTextField();
        NewBuyerCellphoneTextField = new javax.swing.JTextField();
        NewBuyerEmailTextField = new javax.swing.JTextField();
        NewBuyerAddressTextField = new javax.swing.JTextField();
        NewBuyerGenderComboBox = new javax.swing.JComboBox<>();
        NewBuyerSaveButton = new javax.swing.JButton();
        NewBuyerTitleLabel1 = new javax.swing.JLabel();
        NewBuyerResetButton = new javax.swing.JButton();
        NewBuyerCloseButton = new javax.swing.JButton();
        NewBuyerCpfLabel = new javax.swing.JLabel();
        NewBuyerCPFTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(680, 320));
        setMaximumSize(new java.awt.Dimension(600, 450));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 450));
        setResizable(false);

        NewBuyerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeImages/new buyer.png"))); // NOI18N

        NewBuyerNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NewBuyerNameLabel.setText("Nome");

        NewBuyerEmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NewBuyerEmailLabel.setText("Email");

        NewBuyerCellphoneLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NewBuyerCellphoneLabel.setText("Telefone ");

        NewBuyerAddressLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NewBuyerAddressLabel.setText("Endereço");

        NewBuyeGenderLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NewBuyeGenderLabel.setText("Sexo");

        NewBuyerNameTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NewBuyerNameTextField.setForeground(new java.awt.Color(153, 153, 153));
        NewBuyerNameTextField.setText("Inserir nome");
        NewBuyerNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NewBuyerNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewBuyerNameTextFieldFocusLost(evt);
            }
        });
        NewBuyerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBuyerNameTextFieldActionPerformed(evt);
            }
        });

        NewBuyerCellphoneTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NewBuyerCellphoneTextField.setForeground(new java.awt.Color(153, 153, 153));
        NewBuyerCellphoneTextField.setText("Inserir Telefone");
        NewBuyerCellphoneTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NewBuyerCellphoneTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewBuyerCellphoneTextFieldFocusLost(evt);
            }
        });
        NewBuyerCellphoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBuyerCellphoneTextFieldActionPerformed(evt);
            }
        });

        NewBuyerEmailTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NewBuyerEmailTextField.setForeground(new java.awt.Color(153, 153, 153));
        NewBuyerEmailTextField.setText("Inserir Email");
        NewBuyerEmailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NewBuyerEmailTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewBuyerEmailTextFieldFocusLost(evt);
            }
        });

        NewBuyerAddressTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NewBuyerAddressTextField.setForeground(new java.awt.Color(153, 153, 153));
        NewBuyerAddressTextField.setText("Inserir endereço");
        NewBuyerAddressTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NewBuyerAddressTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewBuyerAddressTextFieldFocusLost(evt);
            }
        });
        NewBuyerAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBuyerAddressTextFieldActionPerformed(evt);
            }
        });

        NewBuyerGenderComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NewBuyerGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", " " }));
        NewBuyerGenderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBuyerGenderComboBoxActionPerformed(evt);
            }
        });

        NewBuyerSaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        NewBuyerSaveButton.setText("Salvar");
        NewBuyerSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBuyerSaveButtonActionPerformed(evt);
            }
        });

        NewBuyerTitleLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        NewBuyerTitleLabel1.setText("ADICIONAR CLIENTE");

        NewBuyerResetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reset.png"))); // NOI18N
        NewBuyerResetButton.setText("Resetar");
        NewBuyerResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBuyerResetButtonActionPerformed(evt);
            }
        });

        NewBuyerCloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close Jframe.png"))); // NOI18N
        NewBuyerCloseButton.setText("Sair");
        NewBuyerCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBuyerCloseButtonActionPerformed(evt);
            }
        });

        NewBuyerCpfLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NewBuyerCpfLabel.setText("CPF");

        NewBuyerCPFTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NewBuyerCPFTextField.setForeground(new java.awt.Color(153, 153, 153));
        NewBuyerCPFTextField.setText("Inserir CPF");
        NewBuyerCPFTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NewBuyerCPFTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewBuyerCPFTextFieldFocusLost(evt);
            }
        });
        NewBuyerCPFTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBuyerCPFTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NewBuyerIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NewBuyerTitleLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NewBuyerSaveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NewBuyerResetButton)
                        .addGap(97, 97, 97)
                        .addComponent(NewBuyerCloseButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewBuyerNameLabel)
                            .addComponent(NewBuyerCellphoneLabel)
                            .addComponent(NewBuyerEmailLabel)
                            .addComponent(NewBuyerAddressLabel)
                            .addComponent(NewBuyerCpfLabel)
                            .addComponent(NewBuyeGenderLabel))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewBuyerGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NewBuyerCellphoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                .addComponent(NewBuyerNameTextField)
                                .addComponent(NewBuyerCPFTextField)
                                .addComponent(NewBuyerAddressTextField)
                                .addComponent(NewBuyerEmailTextField)))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(NewBuyerTitleLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NewBuyerIcon)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewBuyerNameLabel)
                    .addComponent(NewBuyerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewBuyerCellphoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewBuyerCellphoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewBuyerEmailLabel)
                    .addComponent(NewBuyerEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewBuyerAddressLabel)
                    .addComponent(NewBuyerAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewBuyerCpfLabel)
                    .addComponent(NewBuyerCPFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewBuyerGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewBuyeGenderLabel))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewBuyerResetButton)
                    .addComponent(NewBuyerSaveButton)
                    .addComponent(NewBuyerCloseButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewBuyerGenderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBuyerGenderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewBuyerGenderComboBoxActionPerformed

    private void NewBuyerSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBuyerSaveButtonActionPerformed
        String name = NewBuyerNameTextField.getText();
        String cellphone = NewBuyerCellphoneTextField.getText();
        String email = NewBuyerEmailTextField.getText();
        String address = NewBuyerAddressTextField.getText();
        String CPF = NewBuyerCPFTextField.getText();
        String gender =(String) NewBuyerGenderComboBox.getSelectedItem();
        
        Buyer buyer = new Buyer(name,cellphone,email,address,gender,CPF);
        
        try{
            Connection con= ConnectionProvider.getCon(); 
            String sql = ("INSERT INTO buyer(name,cellphone,email,address,gender,CPF) VALUES (?,?,?,?,?,?)");
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setString(1,buyer.getName() );
            pst.setString(2,buyer.getCellphone() );
            pst.setString(3,buyer.getEmail() );
            pst.setString(4,buyer.getAddress() );
            pst.setString(5,buyer.getGender() );
            pst.setString(6,buyer.getCPF() );
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Success");
            setVisible(false);
            new NewBuyer().setVisible(true);
            
        }
        catch(SQLException e){
             JOptionPane.showMessageDialog(null,"Error");
        }
             
    }//GEN-LAST:event_NewBuyerSaveButtonActionPerformed

    private void NewBuyerCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBuyerCloseButtonActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Tem certeza?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
        }
    }//GEN-LAST:event_NewBuyerCloseButtonActionPerformed

    private void NewBuyerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBuyerNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewBuyerNameTextFieldActionPerformed

    private void NewBuyerCellphoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBuyerCellphoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewBuyerCellphoneTextFieldActionPerformed

    private void NewBuyerNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewBuyerNameTextFieldFocusGained
        if(NewBuyerNameTextField.getText().equals("Inserir nome")){
            NewBuyerNameTextField.setText("");
            NewBuyerNameTextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_NewBuyerNameTextFieldFocusGained

    private void NewBuyerNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewBuyerNameTextFieldFocusLost
        if(NewBuyerNameTextField.getText().equals("")){
            NewBuyerNameTextField.setText("Inserir nome");
            NewBuyerNameTextField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_NewBuyerNameTextFieldFocusLost

    private void NewBuyerCellphoneTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewBuyerCellphoneTextFieldFocusGained
        if(NewBuyerCellphoneTextField.getText().equals("Inserir Telefone")){
            NewBuyerCellphoneTextField.setText("");
            NewBuyerCellphoneTextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_NewBuyerCellphoneTextFieldFocusGained

    private void NewBuyerCellphoneTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewBuyerCellphoneTextFieldFocusLost
        if(NewBuyerCellphoneTextField.getText().equals("")){
            NewBuyerCellphoneTextField.setText("Inserir Telefone");
            NewBuyerCellphoneTextField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_NewBuyerCellphoneTextFieldFocusLost

    private void NewBuyerEmailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewBuyerEmailTextFieldFocusGained
        if(NewBuyerEmailTextField.getText().equals("Inserir Email")){
            NewBuyerEmailTextField.setText("");
            NewBuyerEmailTextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_NewBuyerEmailTextFieldFocusGained

    private void NewBuyerEmailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewBuyerEmailTextFieldFocusLost
        if(NewBuyerEmailTextField.getText().equals("")){
            NewBuyerEmailTextField.setText("Inserir Email");
            NewBuyerEmailTextField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_NewBuyerEmailTextFieldFocusLost

    private void NewBuyerAddressTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewBuyerAddressTextFieldFocusGained
        if(NewBuyerAddressTextField.getText().equals("Inserir endereço")){
            NewBuyerAddressTextField.setText("");
            NewBuyerAddressTextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_NewBuyerAddressTextFieldFocusGained

    private void NewBuyerAddressTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewBuyerAddressTextFieldFocusLost
        if(NewBuyerAddressTextField.getText().equals("")){
            NewBuyerAddressTextField.setText("Inserir endereço");
            NewBuyerAddressTextField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_NewBuyerAddressTextFieldFocusLost

    private void NewBuyerResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBuyerResetButtonActionPerformed
        setVisible(false);
        new NewBuyer().setVisible(true);
    }//GEN-LAST:event_NewBuyerResetButtonActionPerformed

    private void NewBuyerCPFTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBuyerCPFTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewBuyerCPFTextFieldActionPerformed

    private void NewBuyerAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBuyerAddressTextFieldActionPerformed
        
    }//GEN-LAST:event_NewBuyerAddressTextFieldActionPerformed

    private void NewBuyerCPFTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewBuyerCPFTextFieldFocusGained
        if(NewBuyerCPFTextField.getText().equals("Inserir CPF")){
            NewBuyerCPFTextField.setText("");
            NewBuyerCPFTextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_NewBuyerCPFTextFieldFocusGained

    private void NewBuyerCPFTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewBuyerCPFTextFieldFocusLost
        if(NewBuyerCPFTextField.getText().equals("")){
            NewBuyerCPFTextField.setText("Inserir CPF");
            NewBuyerCPFTextField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_NewBuyerCPFTextFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBuyer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NewBuyeGenderLabel;
    private javax.swing.JLabel NewBuyerAddressLabel;
    private javax.swing.JTextField NewBuyerAddressTextField;
    private javax.swing.JTextField NewBuyerCPFTextField;
    private javax.swing.JLabel NewBuyerCellphoneLabel;
    private javax.swing.JTextField NewBuyerCellphoneTextField;
    private javax.swing.JButton NewBuyerCloseButton;
    private javax.swing.JLabel NewBuyerCpfLabel;
    private javax.swing.JLabel NewBuyerEmailLabel;
    private javax.swing.JTextField NewBuyerEmailTextField;
    private javax.swing.JComboBox<String> NewBuyerGenderComboBox;
    private javax.swing.JLabel NewBuyerIcon;
    private javax.swing.JLabel NewBuyerNameLabel;
    private javax.swing.JTextField NewBuyerNameTextField;
    private javax.swing.JButton NewBuyerResetButton;
    private javax.swing.JButton NewBuyerSaveButton;
    private javax.swing.JLabel NewBuyerTitleLabel1;
    // End of variables declaration//GEN-END:variables
}
