/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Bean.Buyer;
import Dao.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author pedro
 */
public class UpdateBuyer extends javax.swing.JFrame {

    /**
     * Creates new form UpdateBuyer
     */
    public UpdateBuyer() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        UpdateBuyerUpdateButton = new javax.swing.JButton();
        UpdateBuyerResetButton = new javax.swing.JButton();
        UpdateBuyerCloseButton = new javax.swing.JButton();
        UpdateBuyerGenderTextField = new javax.swing.JTextField();
        UpdateBuyerAddressTextField = new javax.swing.JTextField();
        UpdateBuyerEmailTextField = new javax.swing.JTextField();
        UpdateBuyerCellphoneTextField = new javax.swing.JTextField();
        UpdateBuyerNameTextField = new javax.swing.JTextField();
        UpdateBuyerCPFTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UpdateBuyerSearchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setLocation(new java.awt.Point(680, 320));
        setMaximumSize(new java.awt.Dimension(600, 450));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 450));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CPF");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Telefone");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Endereço");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Sexo");

        UpdateBuyerUpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateBuyerUpdateButton.setText("Update");
        UpdateBuyerUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBuyerUpdateButtonActionPerformed(evt);
            }
        });

        UpdateBuyerResetButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateBuyerResetButton.setText("Reset");
        UpdateBuyerResetButton.setMaximumSize(new java.awt.Dimension(79, 27));
        UpdateBuyerResetButton.setMinimumSize(new java.awt.Dimension(79, 27));
        UpdateBuyerResetButton.setPreferredSize(new java.awt.Dimension(79, 27));
        UpdateBuyerResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBuyerResetButtonActionPerformed(evt);
            }
        });

        UpdateBuyerCloseButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateBuyerCloseButton.setText("Close");
        UpdateBuyerCloseButton.setMaximumSize(new java.awt.Dimension(79, 27));
        UpdateBuyerCloseButton.setMinimumSize(new java.awt.Dimension(79, 27));
        UpdateBuyerCloseButton.setPreferredSize(new java.awt.Dimension(79, 27));
        UpdateBuyerCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBuyerCloseButtonActionPerformed(evt);
            }
        });

        UpdateBuyerGenderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBuyerGenderTextFieldActionPerformed(evt);
            }
        });

        UpdateBuyerAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBuyerAddressTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeImages/update buyer.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setText("ATUALIZAR CLIENTE");

        UpdateBuyerSearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        UpdateBuyerSearchButton.setText("Procurar");
        UpdateBuyerSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBuyerSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(357, 357, 357)
                                .addComponent(UpdateBuyerCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(UpdateBuyerGenderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(UpdateBuyerAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(UpdateBuyerCPFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(UpdateBuyerSearchButton)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(UpdateBuyerCellphoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(UpdateBuyerEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(UpdateBuyerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UpdateBuyerUpdateButton)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(148, 148, 148)
                        .addComponent(UpdateBuyerResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateBuyerCPFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBuyerSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateBuyerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateBuyerCellphoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateBuyerEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(UpdateBuyerAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateBuyerGenderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateBuyerUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBuyerResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBuyerCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateBuyerGenderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBuyerGenderTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateBuyerGenderTextFieldActionPerformed

    private void UpdateBuyerAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBuyerAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateBuyerAddressTextFieldActionPerformed

    private void UpdateBuyerResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBuyerResetButtonActionPerformed
        setVisible(false);
        new UpdateBuyer().setVisible(true);
    }//GEN-LAST:event_UpdateBuyerResetButtonActionPerformed

    private void UpdateBuyerCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBuyerCloseButtonActionPerformed
       int a=JOptionPane.showConfirmDialog(null,"Tem certeza?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
        } 
    }//GEN-LAST:event_UpdateBuyerCloseButtonActionPerformed

    private void UpdateBuyerSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBuyerSearchButtonActionPerformed
        String CPF = UpdateBuyerCPFTextField.getText();        
        Buyer buyer = new Buyer("?","?","?","?","?",CPF);        
        try{
            ConnectionProvider.Crud.search(buyer);      
                UpdateBuyerNameTextField.setText(buyer.getName());
                UpdateBuyerCellphoneTextField.setText(buyer.getCellphone());
                UpdateBuyerEmailTextField.setText(buyer.getEmail());
                UpdateBuyerAddressTextField.setText(buyer.getAddress());
                UpdateBuyerGenderTextField.setText(buyer.getGender());                        
        }catch(SQLException e){
             JOptionPane.showMessageDialog(null,"Erro ao conectar no banco de dados");
        }
    }//GEN-LAST:event_UpdateBuyerSearchButtonActionPerformed

    private void UpdateBuyerUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBuyerUpdateButtonActionPerformed
        String name=UpdateBuyerNameTextField.getText();
        String cellphone=UpdateBuyerCellphoneTextField.getText();
        String email=UpdateBuyerEmailTextField.getText();
        String address=UpdateBuyerAddressTextField.getText();
        String gender=UpdateBuyerGenderTextField.getText();
        String CPF=UpdateBuyerCPFTextField.getText();        
        Buyer buyer = new Buyer(name,cellphone,email,address,gender,CPF);
        
        try{
        ConnectionProvider.Crud.update(buyer);
        JOptionPane.showMessageDialog(null, "Success");
        setVisible(false);
        new UpdateBuyer().setVisible(true);
        
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,"Erro na conexao com o banco de dados");
     }
        
                
    }//GEN-LAST:event_UpdateBuyerUpdateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateBuyer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UpdateBuyerAddressTextField;
    private javax.swing.JTextField UpdateBuyerCPFTextField;
    private javax.swing.JTextField UpdateBuyerCellphoneTextField;
    private javax.swing.JButton UpdateBuyerCloseButton;
    private javax.swing.JTextField UpdateBuyerEmailTextField;
    private javax.swing.JTextField UpdateBuyerGenderTextField;
    private javax.swing.JTextField UpdateBuyerNameTextField;
    private javax.swing.JButton UpdateBuyerResetButton;
    private javax.swing.JButton UpdateBuyerSearchButton;
    private javax.swing.JButton UpdateBuyerUpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
